import type { Book } from '../backend';

// Helper function to create mock Principal
const mockPrincipal = (id: string) => ({
  toText: () => id,
  toString: () => id,
} as any);

// Mock books organized by mood categories with generated cover images
export const mockBooksByMood = {
  Happy: [
    {
      title: 'Sunflower Meadows',
      author: 'Iris Bloom',
      coverImageUrl: '/assets/generated/happy-book-1.dim_400x600.png',
      description: 'A heartwarming tale of friendship and golden summer days filled with laughter and joy.',
      publicationYear: BigInt(2024),
      isbn: 'happy-001',
      uploaderId: mockPrincipal('mock-uploader-1'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Fiction',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(280),
      pdfFileUrl: '',
    },
    {
      title: 'The Joy of Painting',
      author: 'Vincent van Gogh',
      coverImageUrl: '/assets/generated/happy-book-2.dim_400x600.png',
      description: 'Finding happiness in every brushstroke and celebrating the beauty of creative expression.',
      publicationYear: BigInt(2024),
      isbn: 'happy-002',
      uploaderId: mockPrincipal('mock-uploader-2'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Non-Fiction',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(320),
      pdfFileUrl: '',
    },
    {
      title: 'Laughter in the Café',
      author: 'Henri Toulouse',
      coverImageUrl: '/assets/generated/happy-book-3.dim_400x600.png',
      description: 'Joyful moments shared over coffee and conversation in a charming Parisian café.',
      publicationYear: BigInt(2023),
      isbn: 'happy-003',
      uploaderId: mockPrincipal('mock-uploader-3'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Fiction',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(240),
      pdfFileUrl: '',
    },
  ],
  Melancholic: [
    {
      title: 'The Bedroom Solitude',
      author: 'Arles Writer',
      coverImageUrl: '/assets/generated/melancholic-book-1.dim_400x600.png',
      description: 'Intimate reflections on loneliness and introspection in a quiet room.',
      publicationYear: BigInt(2024),
      isbn: 'melancholic-001',
      uploaderId: mockPrincipal('mock-uploader-6'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Fiction',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(260),
      pdfFileUrl: '',
    },
    {
      title: 'Rainy Nights in Paris',
      author: 'Émile Zola',
      coverImageUrl: '/assets/generated/melancholic-book-2.dim_400x600.png',
      description: 'Melancholic tales from the city of lights during its darkest hours.',
      publicationYear: BigInt(2023),
      isbn: 'melancholic-002',
      uploaderId: mockPrincipal('mock-uploader-7'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Fiction',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(340),
      pdfFileUrl: '',
    },
    {
      title: 'Autumn Leaves',
      author: 'Paul Verlaine',
      coverImageUrl: '/assets/generated/melancholic-book-3.dim_400x600.png',
      description: 'Poetry of fading seasons and bittersweet memories that linger.',
      publicationYear: BigInt(2024),
      isbn: 'melancholic-003',
      uploaderId: mockPrincipal('mock-uploader-8'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Non-Fiction',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(220),
      pdfFileUrl: '',
    },
  ],
  Adventurous: [
    {
      title: 'Journey to the Stars',
      author: 'Camille Flammarion',
      coverImageUrl: '/assets/generated/adventurous-book-1.dim_400x600.png',
      description: 'An epic voyage through the cosmos discovering new worlds and civilizations.',
      publicationYear: BigInt(2024),
      isbn: 'adventurous-001',
      uploaderId: mockPrincipal('mock-uploader-9'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Science Fiction',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(420),
      pdfFileUrl: '',
    },
    {
      title: 'The Mountain Climber',
      author: 'Paul Cézanne',
      coverImageUrl: '/assets/generated/adventurous-book-2.dim_400x600.png',
      description: 'Conquering peaks and discovering oneself in the majesty of nature.',
      publicationYear: BigInt(2023),
      isbn: 'adventurous-002',
      uploaderId: mockPrincipal('mock-uploader-10'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Non-Fiction',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(380),
      pdfFileUrl: '',
    },
    {
      title: 'Sailing the Mediterranean',
      author: 'Claude Monet',
      coverImageUrl: '/assets/generated/adventurous-book-3.dim_400x600.png',
      description: 'Adventures on the high seas exploring ancient ports and hidden coves.',
      publicationYear: BigInt(2024),
      isbn: 'adventurous-003',
      uploaderId: mockPrincipal('mock-uploader-11'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Fiction',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(350),
      pdfFileUrl: '',
    },
  ],
  Calm: [
    {
      title: 'Zen Garden Reflections',
      author: 'Hokusai Katsushika',
      coverImageUrl: '/assets/generated/calm-book-1.dim_400x600.png',
      description: 'Finding peace and tranquility in the simplicity of a Japanese garden.',
      publicationYear: BigInt(2024),
      isbn: 'calm-001',
      uploaderId: mockPrincipal('mock-uploader-12'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Non-Fiction',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(200),
      pdfFileUrl: '',
    },
    {
      title: 'Whispers of the Forest',
      author: 'Berthe Morisot',
      coverImageUrl: '/assets/generated/calm-book-2.dim_400x600.png',
      description: 'Gentle tales of nature and the soothing sounds of woodland life.',
      publicationYear: BigInt(2023),
      isbn: 'calm-002',
      uploaderId: mockPrincipal('mock-uploader-13'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Fiction',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(250),
      pdfFileUrl: '',
    },
    {
      title: 'Meditation by the Sea',
      author: 'Winslow Homer',
      coverImageUrl: '/assets/generated/calm-book-3.dim_400x600.png',
      description: 'Contemplative moments watching waves and finding inner stillness.',
      publicationYear: BigInt(2024),
      isbn: 'calm-003',
      uploaderId: mockPrincipal('mock-uploader-14'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Non-Fiction',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(180),
      pdfFileUrl: '',
    },
  ],
  Inspiring: [
    {
      title: 'Rise Above',
      author: 'Georgia O\'Keeffe',
      coverImageUrl: '/assets/generated/inspiring-book-1.dim_400x600.png',
      description: 'Stories of triumph over adversity and the power of human resilience.',
      publicationYear: BigInt(2024),
      isbn: 'inspiring-001',
      uploaderId: mockPrincipal('mock-uploader-15'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Non-Fiction',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(310),
      pdfFileUrl: '',
    },
    {
      title: 'Dreams into Reality',
      author: 'Salvador Dalí',
      coverImageUrl: '/assets/generated/inspiring-book-2.dim_400x600.png',
      description: 'Transforming imagination into achievement through creative vision.',
      publicationYear: BigInt(2023),
      isbn: 'inspiring-002',
      uploaderId: mockPrincipal('mock-uploader-16'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Non-Fiction',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(290),
      pdfFileUrl: '',
    },
    {
      title: 'The Courage Within',
      author: 'Frida Kahlo',
      coverImageUrl: '/assets/generated/inspiring-book-3.dim_400x600.png',
      description: 'Finding strength in vulnerability and beauty in imperfection.',
      publicationYear: BigInt(2024),
      isbn: 'inspiring-003',
      uploaderId: mockPrincipal('mock-uploader-17'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Fiction',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(270),
      pdfFileUrl: '',
    },
  ],
  Suspenseful: [
    {
      title: 'Shadows in the Night',
      author: 'Edgar Degas',
      coverImageUrl: '/assets/generated/suspenseful-book-1.dim_400x600.png',
      description: 'A thrilling mystery unfolding in the dark corners of Paris.',
      publicationYear: BigInt(2024),
      isbn: 'suspenseful-001',
      uploaderId: mockPrincipal('mock-uploader-18'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Mystery',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(360),
      pdfFileUrl: '',
    },
    {
      title: 'The Hidden Portrait',
      author: 'John Singer Sargent',
      coverImageUrl: '/assets/generated/suspenseful-book-2.dim_400x600.png',
      description: 'Secrets revealed through a mysterious painting with a dark past.',
      publicationYear: BigInt(2023),
      isbn: 'suspenseful-002',
      uploaderId: mockPrincipal('mock-uploader-19'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Mystery',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(330),
      pdfFileUrl: '',
    },
    {
      title: 'Midnight at the Museum',
      author: 'Mary Cassatt',
      coverImageUrl: '/assets/generated/suspenseful-book-3.dim_400x600.png',
      description: 'Strange occurrences after hours in a world-famous art gallery.',
      publicationYear: BigInt(2024),
      isbn: 'suspenseful-003',
      uploaderId: mockPrincipal('mock-uploader-20'),
      approvalStatus: { __kind__: 'approved' as const, approved: null },
      genre: 'Mystery',
      editCount: BigInt(0),
      createdAt: BigInt(Date.now() * 1000000),
      pageCount: BigInt(300),
      pdfFileUrl: '',
    },
  ],
};

// Trending mock books with generated covers
export const trendingMockBooks: Book[] = [
  {
    title: 'The Starry Night Chronicles',
    author: 'Vincent van Gogh',
    coverImageUrl: '/assets/generated/trending-book-1.dim_400x600.png',
    description: 'A mesmerizing journey through art, passion, and the beauty of the night sky.',
    publicationYear: BigInt(2024),
    isbn: 'trending-001',
    uploaderId: mockPrincipal('mock-uploader-21'),
    approvalStatus: { __kind__: 'approved' as const, approved: null },
    genre: 'Fiction',
    editCount: BigInt(0),
    createdAt: BigInt(Date.now() * 1000000),
    pageCount: BigInt(450),
    pdfFileUrl: '',
  },
  {
    title: 'Impressions of Light',
    author: 'Claude Monet',
    coverImageUrl: '/assets/generated/trending-book-2.dim_400x600.png',
    description: 'Capturing fleeting moments and the ever-changing dance of light and color.',
    publicationYear: BigInt(2024),
    isbn: 'trending-002',
    uploaderId: mockPrincipal('mock-uploader-22'),
    approvalStatus: { __kind__: 'approved' as const, approved: null },
    genre: 'Non-Fiction',
    editCount: BigInt(0),
    createdAt: BigInt(Date.now() * 1000000),
    pageCount: BigInt(380),
    pdfFileUrl: '',
  },
  {
    title: 'The Artist\'s Journey',
    author: 'Paul Gauguin',
    coverImageUrl: '/assets/generated/trending-book-3.dim_400x600.png',
    description: 'From Paris to Tahiti: a quest for artistic truth and personal freedom.',
    publicationYear: BigInt(2023),
    isbn: 'trending-003',
    uploaderId: mockPrincipal('mock-uploader-23'),
    approvalStatus: { __kind__: 'approved' as const, approved: null },
    genre: 'Fiction',
    editCount: BigInt(0),
    createdAt: BigInt(Date.now() * 1000000),
    pageCount: BigInt(410),
    pdfFileUrl: '',
  },
  {
    title: 'Colors of Emotion',
    author: 'Wassily Kandinsky',
    coverImageUrl: '/assets/generated/trending-book-4.dim_400x600.png',
    description: 'Exploring the profound connection between color, music, and human feeling.',
    publicationYear: BigInt(2024),
    isbn: 'trending-004',
    uploaderId: mockPrincipal('mock-uploader-24'),
    approvalStatus: { __kind__: 'approved' as const, approved: null },
    genre: 'Non-Fiction',
    editCount: BigInt(0),
    createdAt: BigInt(Date.now() * 1000000),
    pageCount: BigInt(320),
    pdfFileUrl: '',
  },
  {
    title: 'Café Conversations',
    author: 'Henri de Toulouse-Lautrec',
    coverImageUrl: '/assets/generated/trending-book-5.dim_400x600.png',
    description: 'Intimate stories from the bohemian heart of Montmartre.',
    publicationYear: BigInt(2024),
    isbn: 'trending-005',
    uploaderId: mockPrincipal('mock-uploader-25'),
    approvalStatus: { __kind__: 'approved' as const, approved: null },
    genre: 'Fiction',
    editCount: BigInt(0),
    createdAt: BigInt(Date.now() * 1000000),
    pageCount: BigInt(290),
    pdfFileUrl: '',
  },
];
