/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Text,
});
export const Book = IDL.Record({
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'isbn' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'approvalStatus' : ApprovalStatus,
  'publicationYear' : IDL.Nat,
  'editCount' : IDL.Nat,
  'uploaderId' : IDL.Principal,
});
export const BookSubmission = IDL.Record({
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'isbn' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'approvalStatus' : ApprovalStatus,
  'publicationYear' : IDL.Nat,
  'editCount' : IDL.Nat,
  'uploaderId' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveBookSubmission' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBook' : IDL.Func([IDL.Text], [], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(BookSubmission)], ['query']),
  'getBook' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
  'getBooksByStatus' : IDL.Func([ApprovalStatus], [IDL.Vec(Book)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingSubmissions' : IDL.Func([], [IDL.Vec(BookSubmission)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBookForApproval' : IDL.Func([Book], [], []),
  'updateBook' : IDL.Func([IDL.Text, Book], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Text,
  });
  const Book = IDL.Record({
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'isbn' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'approvalStatus' : ApprovalStatus,
    'publicationYear' : IDL.Nat,
    'editCount' : IDL.Nat,
    'uploaderId' : IDL.Principal,
  });
  const BookSubmission = IDL.Record({
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'isbn' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'approvalStatus' : ApprovalStatus,
    'publicationYear' : IDL.Nat,
    'editCount' : IDL.Nat,
    'uploaderId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveBookSubmission' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBook' : IDL.Func([IDL.Text], [], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(BookSubmission)], ['query']),
    'getBook' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
    'getBooksByStatus' : IDL.Func([ApprovalStatus], [IDL.Vec(Book)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingSubmissions' : IDL.Func(
        [],
        [IDL.Vec(BookSubmission)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBookForApproval' : IDL.Func([Book], [], []),
    'updateBook' : IDL.Func([IDL.Text, Book], [], []),
  });
};

export const init = ({ IDL }) => { return []; };