/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Usage = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Text,
});
export const Book = IDL.Record({
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'pdfFileUrl' : IDL.Text,
  'isbn' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'approvalStatus' : Usage,
  'genre' : IDL.Text,
  'publicationYear' : IDL.Nat,
  'editCount' : IDL.Nat,
  'pageCount' : IDL.Nat,
  'uploaderId' : IDL.Principal,
});
export const BookSubmission = IDL.Record({
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'pdfFileUrl' : IDL.Text,
  'isbn' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'approvalStatus' : Usage,
  'genre' : IDL.Text,
  'publicationYear' : IDL.Nat,
  'totalPages' : IDL.Nat,
  'editCount' : IDL.Nat,
  'uploaderId' : IDL.Principal,
});
export const ReadingProgress = IDL.Record({
  'bookIsbn' : IDL.Text,
  'userId' : IDL.Principal,
  'lastUpdated' : IDL.Int,
  'pagesRead' : IDL.Nat,
});
export const Rating = IDL.Record({
  'bookIsbn' : IDL.Text,
  'userId' : IDL.Principal,
  'stars' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'isAuthor' : IDL.Bool,
});
export const EditRequest = IDL.Record({
  'bookIsbn' : IDL.Text,
  'authorId' : IDL.Principal,
  'message' : IDL.Opt(IDL.Text),
});
export const Recommendation = IDL.Record({
  'book' : Book,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRating' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'approveBookSubmission' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearEditRequests' : IDL.Func([IDL.Text], [], []),
  'deleteAccount' : IDL.Func([IDL.Opt(IDL.Principal)], [], []),
  'deleteBook' : IDL.Func([IDL.Text], [], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(BookSubmission)], ['query']),
  'getAllUserProgress' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Tuple(IDL.Text, ReadingProgress))],
      ['query'],
    ),
  'getBook' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
  'getBookAverageRating' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'getBookCompletedUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getBookRatings' : IDL.Func([IDL.Text], [IDL.Vec(Rating)], ['query']),
  'getBookmarkedBooks' : IDL.Func([IDL.Principal], [IDL.Vec(Book)], ['query']),
  'getBooksByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'getBooksByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'getBooksByGenreAndAuthor' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Book)],
      ['query'],
    ),
  'getBooksByStatus' : IDL.Func([Usage], [IDL.Vec(Book)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEditRequests' : IDL.Func([IDL.Text], [IDL.Vec(EditRequest)], ['query']),
  'getPendingSubmissions' : IDL.Func([], [IDL.Vec(BookSubmission)], ['query']),
  'getPersonalizedRecommendations' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Recommendation)],
      ['query'],
    ),
  'getReadingProgress' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Opt(ReadingProgress)],
      ['query'],
    ),
  'getTrendingBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getUserBookProgress' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ReadingProgress)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func(
      [IDL.Principal],
      [IDL.Record({ 'isAuthor' : IDL.Bool, 'systemRole' : UserRole })],
      ['query'],
    ),
  'isBookBookmarked' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'promoteToAuthor' : IDL.Func([IDL.Principal], [], []),
  'requestMoreEdits' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPreferredGenres' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'submitBookForApproval' : IDL.Func([Book], [], []),
  'toggleBookmark' : IDL.Func([IDL.Text], [], []),
  'updateBook' : IDL.Func([IDL.Text, Book], [], []),
  'updateReadingProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Usage = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Text,
  });
  const Book = IDL.Record({
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'pdfFileUrl' : IDL.Text,
    'isbn' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'approvalStatus' : Usage,
    'genre' : IDL.Text,
    'publicationYear' : IDL.Nat,
    'editCount' : IDL.Nat,
    'pageCount' : IDL.Nat,
    'uploaderId' : IDL.Principal,
  });
  const BookSubmission = IDL.Record({
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'pdfFileUrl' : IDL.Text,
    'isbn' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'approvalStatus' : Usage,
    'genre' : IDL.Text,
    'publicationYear' : IDL.Nat,
    'totalPages' : IDL.Nat,
    'editCount' : IDL.Nat,
    'uploaderId' : IDL.Principal,
  });
  const ReadingProgress = IDL.Record({
    'bookIsbn' : IDL.Text,
    'userId' : IDL.Principal,
    'lastUpdated' : IDL.Int,
    'pagesRead' : IDL.Nat,
  });
  const Rating = IDL.Record({
    'bookIsbn' : IDL.Text,
    'userId' : IDL.Principal,
    'stars' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'isAuthor' : IDL.Bool });
  const EditRequest = IDL.Record({
    'bookIsbn' : IDL.Text,
    'authorId' : IDL.Principal,
    'message' : IDL.Opt(IDL.Text),
  });
  const Recommendation = IDL.Record({ 'book' : Book, 'reason' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRating' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'approveBookSubmission' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearEditRequests' : IDL.Func([IDL.Text], [], []),
    'deleteAccount' : IDL.Func([IDL.Opt(IDL.Principal)], [], []),
    'deleteBook' : IDL.Func([IDL.Text], [], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(BookSubmission)], ['query']),
    'getAllUserProgress' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Tuple(IDL.Text, ReadingProgress))],
        ['query'],
      ),
    'getBook' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
    'getBookAverageRating' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getBookCompletedUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getBookRatings' : IDL.Func([IDL.Text], [IDL.Vec(Rating)], ['query']),
    'getBookmarkedBooks' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Book)],
        ['query'],
      ),
    'getBooksByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'getBooksByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'getBooksByGenreAndAuthor' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Book)],
        ['query'],
      ),
    'getBooksByStatus' : IDL.Func([Usage], [IDL.Vec(Book)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEditRequests' : IDL.Func([IDL.Text], [IDL.Vec(EditRequest)], ['query']),
    'getPendingSubmissions' : IDL.Func(
        [],
        [IDL.Vec(BookSubmission)],
        ['query'],
      ),
    'getPersonalizedRecommendations' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Recommendation)],
        ['query'],
      ),
    'getReadingProgress' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Opt(ReadingProgress)],
        ['query'],
      ),
    'getTrendingBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getUserBookProgress' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ReadingProgress)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func(
        [IDL.Principal],
        [IDL.Record({ 'isAuthor' : IDL.Bool, 'systemRole' : UserRole })],
        ['query'],
      ),
    'isBookBookmarked' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'promoteToAuthor' : IDL.Func([IDL.Principal], [], []),
    'requestMoreEdits' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPreferredGenres' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'submitBookForApproval' : IDL.Func([Book], [], []),
    'toggleBookmark' : IDL.Func([IDL.Text], [], []),
    'updateBook' : IDL.Func([IDL.Text, Book], [], []),
    'updateReadingProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };